permalink: /:categories/:title

pygments: true

site_url: http://www.miguelmota.com

theme:

  site_name: Miguel Mota | Web Developer

  google_analytics_uid: UA-12642068-1

  disqus_shortname: miguelmota

  homepage_featured: 1

  homepage_posts: 100

  featured_wordcount: 70